name: CI/CD Workflow
on:
  push:
    branches:
      - main
pull_request:
  branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest
      - name: Deploy to GCP
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: my-service
          image: gcr.io/my-project/my-service
          project_id: my-project
          region: us-central1
          service_account_key: ${{ secrets.GCP_SA_KEY }}
step:
name: check out code
uses: actions/checkout@v2
name : Set up Python 3.8
uses: actions/setup-python@v2
with:
python-version: 3.8
name: Install dependencies
run: |
python -m pip install --upgrade pip
pip install -r requirements.txt
name: Run tests
run: |
pytest
echo "no Test specified"
name : Deploy to GCP                   
